# -*- coding: utf-8 -*-
"""box,voilin,swarmplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19dH5m95eT7RMb6agzO23aOVwLCCHsjS_
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


df = pd.read_csv('StudentsPerformance.csv')

a = df.head()



plt.figure(figsize = (10,4) , dpi = 200)
# x and y can be switched too
sns.boxplot(data = df ,y = 'reading score' , x = 'parental level of education' , hue ='test preparation course' ,palette ='Set2')
plt.legend(bbox_to_anchor=(1.05,1))

plt.figure(figsize = (10,4) , dpi = 200)
# x and y can be switched too
# violinplot is a mirror KDE
sns.violinplot(data = df ,y = 'reading score' , x = 'parental level of education' ,hue='test preparation course'  ,palette ='Set2' ,split=True,inner='quartile') 
# plt.legend(bbox_to_anchor=(1.05,1))

plt.figure(figsize = (10,4) , dpi = 200)
sns.swarmplot(data = df , x ='math score', size=2 , y='gender', hue = 'test preparation course',dodge=True)
plt.legend(bbox_to_anchor=(1.05,0.5))



















