# -*- coding: utf-8 -*-
"""Joint&PairPlot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19dH5m95eT7RMb6agzO23aOVwLCCHsjS_
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


df = pd.read_csv('StudentsPerformance.csv')

a = df.head()



sns.jointplot(data = df , x = 'math score' , y = 'reading score',kind='kde',shaded=True ,hue='gender')

sns.pairplot(data = df,hue='gender',diag_kind ='hist' , corner=True)





















