# -*- coding: utf-8 -*-
"""MatrixPlots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19dH5m95eT7RMb6agzO23aOVwLCCHsjS_
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


df = pd.read_csv('country_table.csv')

a = df.head()


df = df.set_index('Countries')

plt.figure(dpi=200)
sns.heatmap(df.drop('Life expectancy' , axis =1),lw=0.5 ,annot=True,cmap='viridis')  # center = 40

plt.figure(dpi=200)
sns.clustermap(df.drop('Life expectancy' , axis =1),lw=0.5 ,annot=True,cmap='viridis',col_cluster=True)  # center = 40



















