# -*- coding: utf-8 -*-
"""StatisticswithinCategory.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19dH5m95eT7RMb6agzO23aOVwLCCHsjS_
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


df = pd.read_csv('dm_office_sales.csv')

a = df.head()

a

df['division'].value_counts()

plt.figure(figsize = (10,4) , dpi = 200)
sns.countplot(data = df , x ='level of education' ,hue= 'division' , palette ='Set2')
# plt.ylim(90,260)

plt.figure(figsize = (10,4) , dpi = 200)

sns.barplot(data = df  , x = 'level of education' , y='salary',estimator = np.mean,ci ='sd',hue='division')
plt.legend(bbox_to_anchor=(1.05,1))

sns.kdeplot(data =df , x = 'salary')

np.random.seed(42)
sampleages = np.random.randint(0,100,200)
sampleages

sampleages = pd.DataFrame(sampleages , columns  = ['age'])
sampleages

sns.rugplot(data = sampleages , x = 'age')

sns.histplot(data = sampleages , x = 'age')

sns.displot(data = sampleages , x = 'age' , rug = True , bins = 30 , kde  = True)

sns.kdeplot(data= sampleages , x= 'age' , clip = [0,100] , bw_adjust = 0.1 , shade  = True)





